beardedspice/beardedspice

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/DeezerStrategy.h
BeardedSpice/DeezerStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

Add a Deezer strategy to fix #57

Add Deezer Strategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/FocusAtWillStrategy.h
BeardedSpice/FocusAtWillStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

Add media strategy for [focusatwill.com](http://focusatwill.com) :notes: :smile_cat:

Add focus@will strategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/MediaStrategyRegistry.m
BeardedSpice/PocketCastsStrategy.h
BeardedSpice/PocketCastsStrategy.m

Added PocketCasts support.
Related issue https://github.com/beardedspice/beardedspice/issues/81

Added PocketCasts support

---

BeardedSpice/AppDelegate.m

Hey guys. This patch solves #20, #29 and #108 for me.
PS: I'm not a Cocoa guru, so don't kick me hard ;)

Aggressively restore media keys subscription

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/MediaStrategyRegistry.m
BeardedSpice/SomaFmStrategy.h
BeardedSpice/SomaFmStrategy.m
Podfile.lock
README.md

Support for [SomaFM](http://somafm.com/listen) web player.
- play/pause toggle of course
- pause on tab switch
- favorite
- there's no next/previous in this player
- current artist + song name

Add SomaFM support.

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/DigitallyImportedStrategy.h
BeardedSpice/DigitallyImportedStrategy.m
BeardedSpice/MediaStrategyRegistry.m

See #142 -- had other changes dirtying my master branch.

Updated digitally imported media strategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/LogitechMediaServerStrategy.h
BeardedSpice/LogitechMediaServerStrategy.m
BeardedSpice/MediaStrategyRegistry.m

Don't know how useful this is because the ip is probably different in other cases.

adding Logitech Media Server strategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/MediaStrategyRegistry.m
BeardedSpice/SaavnStrategy.h
BeardedSpice/SaavnStrategy.m
Podfile.lock
README.md

Add a Saavn strategy for http://saavn.com

Add Saavn Strategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/MediaStrategyRegistry.m
BeardedSpice/WonderFmStrategy.h
BeardedSpice/WonderFmStrategy.m

Adds support for [WonderFM](http://wonder.fm) player:
* play/pause toggle (handles hidden controls on initial page load)
* pause
* next
* no previous support

Adding WonderFM Strategy

---

BeardedSpice/MediaStrategies/EightTracksStrategy.m

Updated 8tracks strategy after changes broke it.

Fixed & improved 8tracks strategy

---

BeardedSpice/MediaStrategies/VkStrategy.m

Use VK.com pop-up player to control the music and obtain current track info. This PR makes the plugin working on every page, not only "My Music".

Make VK.com plugin working on all pages

---

BeardedSpice/MediaStrategies/SomaFmStrategy.m

Control markup changed, this tracks that update.
Added playlist art for track info, there is no album art.

Fix SomaFM controls, add art to track info

---

BeardedSpice/MediaStrategies/SongzaStrategy.m

Includes track title, artist, album art.
There is no per song favorite, Songza uses voting.

Add track info, album art, and isPlaying for Songza

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/MediaStrategies/RhapsodyStrategy.h
BeardedSpice/MediaStrategies/RhapsodyStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

This PR adds toggle, pause, next, like and previous support for the Rhapsody web player. The friendly album name isn't always available without an extra API call. If it's not available, it should return nothing. 
Please let me know if there's anything I forgot and I will update :)
@Stillness-2

Closes #279 - Rhapsody Support

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/MusicForProgrammingStrategy.h
BeardedSpice/MediaStrategies/MusicForProgrammingStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

- all APIs implemented that are possible
- site has long music sets rather than traditional short tracks
@Stillness-2 totally understand if you reject this if you think this site doesn't fit the traditional music site pattern. It's unusual. But it's fantastic for coding :)

Add MusicForProgramming.net strategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/NetflixStrategy.h
BeardedSpice/MediaStrategies/NetflixStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

- implemented toggle, pause, isPlaying, track info title
- site does not support: fav, track artist, track art
- skip forward and back probably possible but requires sending key press events
- fixes #61, replaces PR #126, thanks @martijnengler for the start

Add Netflix strategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/AudibleStrategy.h
BeardedSpice/MediaStrategies/AudibleStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

- fav sets a bookmark
- prev skips back 30 seconds
- title/author oddly not available but we show artwork, chapter, and time
- fixes #62

Add Audible strategy

---

BeardedSpice/MediaStrategies/OvercastStrategy.m

- added isPlaying, pause
- added full track info

Update Overcast strategy for new API

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/BugsMusicStrategy.h
BeardedSpice/MediaStrategies/BugsMusicStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

[BugsMusic](http://www.bugs.co.kr) is music streaming service in South Korea.
I've implemented all methods.

Add BugsMusic strategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/MediaStrategies/WatchaPlayStrategy.h
BeardedSpice/MediaStrategies/WatchaPlayStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

Replaces and closes #349 (this is just a rebase and squash of that, thanks @Reevid)

Support WatchaPlay(https://play.watcha.net)

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/DailymotionStrategy.h
BeardedSpice/MediaStrategies/DailymotionStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

Play / Pause / Show Info / (un)like are working for playlists and single videos.
No controller for next nor previous when playing a playlist because no button are available on the original website.
Note that you have to use HTML5 version of dailymotion (read the comments in DailymotionStrategy.m)!
References to #363

[App Support] Dailymotion

---

BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/KCRW.plist
BeardedSpice/MediaStrategies/versions.plist

Strategy for integrating BeardedSpice with KCRW.com
toggle, previous, next, and pause all implemented, although pause is the same as toggle

Added KCRW strategy 

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/ProductHunt.plist
BeardedSpice/MediaStrategies/versions.plist
README.md

As asked in issue #385
- toggle
- previous
- next
- favorite
- pause
- isPlaying
- trackInfo

Add ProductHunt strategy

---

BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/Beatport.js
BeardedSpice/MediaStrategies/versions.plist
README.md

https://beatport.com
Closes #53

Add Beatport support

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/BSAppleScriptSupport.m
BeardedSpice/BeardedSpice-Info.plist
BeardedSpice/BeardedSpiceSuite.sdef

Added some initial AppleScript support, playpause/next/previous commands. As well as "fullTitle" property to fetch metadata.
Looking for this to integrate with our Airfoil Satellite app, but probably useful for everyone.

Added basic AppleScript support

---

BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/Stripewaves.js
BeardedSpice/MediaStrategies/versions.plist

This is a new media strategy for the electronic music platform Stripewaves.com.

Added a new media strategy for Stripewaves.com

---

BeardedSpice/MediaStrategies/Anghami.js
BeardedSpice/MediaStrategies/versions.plist

Anghami is a music streaming service for the middle east. URL: play.anghami.com

Added Anghami strategy

---

BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/CozyCloud.js
BeardedSpice/MediaStrategies/versions.plist
README.md

Add the support of the Music application of Cozy Cloud ([more about cozy-music](https://github.com/cozy-labs/cozy-music)).

Add Cozy Cloud Music app support

---

BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/AppleDeveloper.js
BeardedSpice/MediaStrategies/versions.plist
README.md

Add support for Apple Developer
Supports:
Toggle
Pause
Track info

Add Apple Developer support

---

BeardedSpice/MediaStrategies/BE-AT.TV.js
BeardedSpice/MediaStrategies/versions.plist

The play/pause toggle works, the next button works, and there's no "favorite" feature on be-at.tv. As far as I can tell, the back button doesn't actually do anything on the site, so the keyboard shortcut here doesn't work as well.

Add strategy for be-at.tv

---

BeardedSpice/MediaStrategies/RedditMusic.js
BeardedSpice/MediaStrategies/versions.plist

Adding new media strategy for the reddit music player.

Issue #511 - Fix for Reddit Music Player

---

BeardedSpice/MediaStrategies/Pandora.js
BeardedSpice/MediaStrategies/versions.plist

Implement favorite functionality in Pandora Strategy.

Update Pandora Strategy

---

BeardedSpice/MediaStrategies/PhishTracks.js
BeardedSpice/MediaStrategies/versions.plist

Was unsure is the "pause" action was only called if isPlaying is true, or if I needed to check for that.

Implemented PhishTracks.com Strategy

---

BeardedSpice/MediaStrategies/Zvooq.js
BeardedSpice/MediaStrategies/versions.plist

http://zvooq.com/ media strategy

Zvooq media strategy

---

BeardedSpice/MediaStrategies/PhishIn.js
BeardedSpice/MediaStrategies/versions.plist

Support for phish.in

---

BeardedSpice/MediaStrategies/Lynda.js
BeardedSpice/MediaStrategies/versions.plist

Added strategy for https://www.lynda.com

Add Lynda Strategy

---

BeardedSpice/MediaStrategies/Saavn.js
BeardedSpice/MediaStrategies/versions.plist

- Added trackInfo (name, album, album-art)
- Implemented the isPlaying function
- Tested with Safari 10 and Chrome 56

Updated Saavn.js to v2

---

BeardedSpice/MediaStrategies/Synology.js
BeardedSpice/MediaStrategies/versions.plist

Changed detection script to make sure the baseurl check doesn't cause errors on sites that do not have it set. Fixing https://github.com/beardedspice/beardedspice/issues/637

Improved Synology Audiostation detection.

---

BeardedSpice/MediaStrategies/Deezer.js
BeardedSpice/MediaStrategies/versions.plist

The Deezer strategy was broken.
The previous dzPlayer variable was not available in the context.

Update the Deezer strategy #276

---

BeardedSpice/MediaStrategies/Laracasts.js
BeardedSpice/MediaStrategies/versions.plist

This is an updated strategy for one that was proposed but never merged in https://github.com/beardedspice/beardedspice/pull/182

Provide strategy for Laracasts

---

BeardedSpice/MediaStrategies/Pandora.js
BeardedSpice/MediaStrategies/versions.plist

Made query selector for Tuner__Controls element more generic to handle Pandora's change from a div to a span.

Fixing Pandora Media Strategy

---

BeardedSpice/MediaStrategies/Eggheadio.js
BeardedSpice/MediaStrategies/versions.plist

Egghead.io's website was updated and the controls no longer worked, this PR fixes that.

Update Egghead.io media strategy to v2

---

BeardedSpice/MediaStrategies/SiriusXM.js
BeardedSpice/MediaStrategies/versions.plist
README.md

This is for sirius xm's online streaming webapp.
I couldn't find a good image to pluck, but everything else is handled.

added siriusxm media strategy

---

BeardedSpice/MediaStrategies/Youtube.js
BeardedSpice/MediaStrategies/versions.plist

Update YouTube strategy

---

BeardedSpice/MediaStrategies/YandexMusic.js
BeardedSpice/MediaStrategies/YandexRadio.js
BeardedSpice/MediaStrategies/versions.plist

Migrate to official externalAPI of Yandex music services. Now we can control player and get track information without using DOM.

Updated MediaStrategies for Yandex services

---

BeardedSpice/MediaStrategies/PinchyDon.js
BeardedSpice/MediaStrategies/versions.plist

Thanks for making such a great app. This will make it a _tiny_ bit better :)

[App Support] pinchyandfriends.com

---

README.md

Hey! I spent 20 minutes to figure out how to use BeardedSpice & Safari.
And now I want to make this process easier for others 🙂 
- Rename "Download" → "Install"  (As new user you serarch for "How to Install" and not just "Download)
- Add link for Safari users

Readme.md: Clarify Install section
