beardedspice/beardedspice

README.md

`pod setup` step was needed on my laptop when installing the dependencies. Running just `pod install` would give and error complaining that ~/.cocoapods folder did not exist.

Add pod setup to dependencies installation steps

---

BeardedSpice/PandoraStrategy.m

These are mainly cosmetic, and don’t change functionality. Using `querySelectorAll` to select the first (`0`) element is unnecessary: we can simply use `querySelector`. In addition, `next` and `pause` have no reason to be functions.

Small changes to Pandora’s strategy

---

BeardedSpice/AppDelegate.m

Allows BeardedSpice to reassert control over the media keys without restarting or opening the preferences.
Makes BeardedSpice the active application when the menu is opened, so that SPMediaKeyTap intercepts the key taps instead of deferring to the next application.

Activate when opening menu

---

BeardedSpice/YandexMusicStrategy.m

Resolves this issue https://github.com/beardedspice/beardedspice/issues/76
Yandex Music is also on .ua, .kz, and .by TLDs, so I decided not to name them all and just put the TLD under wildcard

Added other TLDs for Yandex Music.

---

BeardedSpice/AppDelegate.m

If a notification is requested but the current strategy doesn't provide track info, nothing is shown. This is fine when controlling the player, but unexpected (for the user) when explicitly pressing the Track Info hotkey.
This PR adds a default notification to be used as a fallback when the app is unable to get track info (unsupported by current strategy, or nothing playing in the current native app). It only gets triggered on the notification hotkey callback - all other keys continue to show no notification.

Default notification

---

BeardedSpice/MediaStrategies/GoogleMusicStrategy.m

Example:
On the JavaScript side, #innerHTML was being used instead of #innerText, which results in special HTML characters things like `&` displayed as `&amp;`

Fixed Google Music notification issue with HTML special characters

---

BeardedSpice/MediaStrategies/SoundCloudStrategy.m

We are limited in the track info we can provide for Soundcloud because "Artist" and "Album" are not fields that Soundcloud is aware of. As such, we provide "Track Title" and the "Soundcloud Username" as a pseudo album name. Better than nothing.

Added trackInfo for Soundcloud

---

BeardedSpice/MediaStrategies/WonderFmStrategy.m

* Fixes track artist to display properly (previously duplicated track name due to changes on Wonder side)
* Updated track name selector to use new `track_name` class

Updated Wonder fm track info selectors to fix track artist and use available classes

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/MediaStrategies/NRKStrategy.h
BeardedSpice/MediaStrategies/NRKStrategy.m
BeardedSpice/MediaStrategyRegistry.m

I was unable to build the application locally, so I haven't been able to veriy if it works. I know the javascript-snippets work when I run them in my console.
The error I got from the build was:
```
ld: library not found for -lMASPreferences
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I tried opening the `.xcworkspace` instead, but I'm unable to do any builds from there. Any ideas?

Add strategy for NRK

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/MediaStrategies/PlexWebStrategy.h
BeardedSpice/MediaStrategies/PlexWebStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

This adds initial support for Plex. I reached out to see if there is a better way to handle this than just clicking DOM elements, as that could break at any point, but it works.
This fixes #56.
Known issues:
I am experiencing problems when I have 2 Plex Web windows open at
the same time. However, in normal usage I suspect this is more of an
edge-case than anything else.
(I am not convinced this isn't just an issue with BeardedSpice in general anyways)

Add initial Plex Web support.

---

BeardedSpice/MediaStrategies/YouTubeStrategy.m

Originally intended to fix #281, but there already is a fix for that somewhere (see #257)
Still creating a PR, just-in-case, because it's more than just a fix: 
* Doesn't rely on the deprecated [Youtube Player JS API](https://developers.google.com/youtube/js_api_reference?hl=en)
* Implements isPlaying method
* Implements trackInfo method w/ Track, Artist, Thumbnail
Cheers.

Changes in YoutubeStrategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/BeardedSpiceUserDefaults.plist
BeardedSpice/MediaStrategies/BBCRadioStrategy.h
BeardedSpice/MediaStrategies/BBCRadioStrategy.m
BeardedSpice/MediaStrategyRegistry.m
README.md

Should support all BBC Radio stations listed at
http://www.bbc.co.uk/radio
This includes Radio 1,2,3,4,5,6, World Service, and about 40 local stations.
Track info uses the site-optional song lister, else falls back to the more
generic show information.
Resolves #194

Add BBC Radio strategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/NativeAppTabRegistry.m
BeardedSpice/Tabs/VLC.h
BeardedSpice/Tabs/VLCTabAdapter.h
BeardedSpice/Tabs/VLCTabAdapter.m
README.md

Putting this up for comments as I've never done an app adapter.
The scripting model for VLC has multiple windows and documents, which makes sense. My approach to finding the right object to receive the controls seems hack-ey - I compare the document names against the app's idea of the currently selected media name. Seems to work, but it doesn't make me happy.
@Coder-256 I think you were playing with this too (noticed your question on SO) and I think I ran into exactly the same problems. See what you think of this approach.
@Stillness-2 I think I may have missed something about the API, is there a better way I should be looking through an app's multiple windows? (key() and isEqual() worry me, I should probably be doing something with those eh?) :)
Might address #347

Add VLC app support

---

BeardedSpice/MediaStrategies/WonderFmStrategy.m
README.md

Wonder.fm launched a redesigned site on 2/17/16. They also launched the Primary (electronic) and White Label (hip hop) sites. This PR updates the Wonder strategy to work with the new site design.
See #359 for the additional support for Primary and White Label strategies.

Update Wonder FM strategy to work with Wonder 2.0

---

BeardedSpice/AppDelegate.h
BeardedSpice/AppDelegate.m

The variable `remoteControlDemonEnabled` should be spelled `remoteControlD`__`a`__`emonEnabled`.

Fixed spelling error (demon -> daemon).

---

BeardedSpice/MediaStrategies/BrainFm.plist
BeardedSpice/MediaStrategies/Vessel.plist

Now these files are valid by the plutil utility and are viewable in
xcode

Make it valid by the plutil utility and xcode

---

BeardedSpice/BSMediaStrategy.m
BeardedSpice/MediaStrategies/PlexWeb.js
BeardedSpice/MediaStrategies/versions.plist

1. Still trying to fix Plex's new UI, but the fix is now backwards compatible, see https://github.com/beardedspice/beardedspice/pull/379
2. While trying to fix this, I got stuck for a few hours with the new JS format for "accepts". Plex is the only strategy using this, so I don't think it has surfaced. It seems like the Google Chrome 46 hack was executing the plex web "accepts" strategy function too early. That is why I want to add the addExecutionStringToScript method call.
In debugging, the difference is like so: 
```
2016-07-16 13:34:25.410 BeardedSpice[77308:4000369] heyyyyyyyyyy
2016-07-16 13:34:25.411 BeardedSpice[77308:4000369] (function accepts() {
return (window.PLEXWEB != undefined || document.querySelector('#plex') != null);
})();
2016-07-16 13:34:25.411 …
```

Fix Plex tabs and new JS script strategy

---

BeardedSpice/MediaStrategies/PlexWeb.js
BeardedSpice/MediaStrategies/versions.plist

I jumped the gun a bit on https://github.com/beardedspice/beardedspice/pull/449
This PR fixes the toggle functionality, which has been broken I think in master?
I'm on Plex Web 2.7.0 (latest) and I tested all major functionality
- Music/video play/pause work
- next/previous with music work
- all music/video info appears correctly in the menubar info

Fix plex toggle strategy

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/NativeAppTabRegistry.m
BeardedSpice/Tabs/Downcast.h
BeardedSpice/Tabs/DowncastTabAdapter.h
BeardedSpice/Tabs/DowncastTabAdapter.m
README.md

#355 
~~An update for Downcast which adds the required AppleScript support for this is currently awaiting review in the Mac App Store (submitted on 8/7/16).~~ The most recent version of [Downcast (v2.9.16)](https://itunes.apple.com/us/app/downcast/id668429425?mt=12) contains the required AppleScript support.

Adds support for Downcast (Mac OS)

---

BeardedSpice/MediaStrategies/MixCloud.js
BeardedSpice/MediaStrategies/MixcloudBeta.js
BeardedSpice/MediaStrategies/versions.plist

Hey guys,
I am one of Mixcloud's developers and we recently launched our new beta site. You can go [here](https://www.mixcloud.com/beta/join) if you would like to join.
The CSS class names on the player have changed so Bearded Spice is currently broken on the Beta site. I created a second MediaStrategy called `MixcloudBeta.js` since both sites are running at the moment. When we launch the new site I will make the necessary changes and merge the two files.

Mixcloud beta compatibility

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpiceControllers/BSCService.h
BeardedSpiceControllers/BSCService.m
BeardedSpiceControllers/Controllers/BSHeadphoneStatusListener.h
BeardedSpiceControllers/Controllers/BSHeadphoneStatusListener.m

I noticed this bug while using the app. If you unplug apple earphones and then plug them back in, media controls from the headphones stop working(volume +- and toggle). Running refreshMikeys a few seconds after headphones are plugged back in seems to fix the issue.

Fix mike not working after it's unplugged and plugged back in

---

BeardedSpice/MediaStrategies/GoogleMusic.js
BeardedSpice/MediaStrategies/versions.plist

- I have slightly updated the Google Music Media Strategy. 
- The element ID for album artwork is `playerBarArt`, not `playingBarArt` which the strategy was using. 
- This update allows BeardedSpice to correctly display track info for Google Music tracks.

Updated Google Music Media Strategy

---

BeardedSpice/Tabs/iTunesTabAdapter.m

See [issue #509](https://github.com/beardedspice/beardedspice/issues/509) where I have laid out the problem.

Fixed "No Track" bug in title return for iTunesTabAdapter

---

BeardedSpice/MediaStrategies/BandCampWhiteLabel.js
BeardedSpice/MediaStrategies/versions.plist

Some record labels are now white labelling Bandcamp, so the URL no longer contains any reference to bandcamp.com. This means that BeardedSpice fails to recognise these as Bandcamp.
I have added a new Media Strategy (copied from bandcamp.js) which detects these white labels by reading the siteroot variable. Tested successfully on http://furtherrecords.org/album/anterior-space and http://recordstore.planetgroucho.com/album/motion-sickness
Thanks!

Added strategy to deal with band camp white label sites

---

BeardedSpiceControllers/Controllers/DDHidLib/DDHidAppleRemote.m

The original white plastic Apple Remote has a different cookie string for the play/pause button.
- Play/Pause Button:
- White Plastic: `33_23_21_20_2_33_23_21_20_2_` (Added)
- Aluminum: `33_21_20_8_2_33_21_20_8_2_`
- Sleep Button:
- White Plastic: `37_33_21_20_2_37_33_21_20_2_` (Added)
- Aluminum: `35_31_19_18_35_31_19_18_`
Tested on OS X El Capitan 10.11.6.

Support white plastic Apple Remote

---

BeardedSpice/MediaStrategies/Udemy.js
BeardedSpice/MediaStrategies/versions.plist

* Replaced Previous and Next - The "Previous" lecture button is now
missing and while "Next" lecture could still be implemented, I opted to
replace the functionality. I made "Next" scrub forward 15 seconds
and "Previous" scrub backwards 15 seconds as in the GUI.
* Updated the selectors to handle the newer non-iFrame Angular UI.

Update Udemy MediaStrategy for Late 2016

---

Scripts/Resources/appcast.xmlTemplate
publish/beardedspice-appcast.xml

This should fix the release notes.
The current https://htmlpreview.github.com/... doesn't work because it redirects to http://htmlpreview.github.io/...
This uses https://htmlpreview.github.io/ so it doesn't redirect to github.io and is served over https

Fixed release notes

---

BeardedSpice/MediaStrategies/WonderFm.js
BeardedSpice/MediaStrategies/versions.plist

Due to a wonderfm-update needed to update CSS-selectors and use dispatchEvent
Info: I tried to refactor dispatchEvent into a local function inside a closure
doing an iife worked (at least it returned the object), but did not create a closure

Fixed wonderfm controls, added prev-track functionality

---

BeardedSpice/MediaStrategies/BandCampWhiteLabel.js
BeardedSpice/MediaStrategies/versions.plist

Sometime the siteroot check could cause errors in unrelated websites, we
should check it before using it.

BandCamp White Label : be more defensive with siteroot

---

BeardedSpice/MediaStrategies/Pandora.js
BeardedSpice/MediaStrategies/versions.plist

Please see https://github.com/beardedspice/beardedspice/pull/545 for some previous discussion on this work.
Because of when things are evaluated (strategy load vs. web page context), it turns out to be pretty tricky to use additional functions as was proposed in my previous pull request. I determined that checking for the presence of `div.Tuner__Controls` reliably detects the new UI, so I used that since it's pretty concise.
I've tested this with both the old and new UIs. I think it makes sense to implement this in the existing strategy so that no one has to modify their BeardedSpice settings: they'll just get support for the new UI automatically, and BeardedSpice will work when they start to use the new UI instead of the old UI. If Pandora drops the old UI, we can simplify this strategy …

Add support for optional new Pandora UI

---

BeardedSpice/MediaStrategies/Stingray.js
BeardedSpice/MediaStrategies/versions.plist

Added a media strategy for the canadian web music streaming service.
There is no previous and favorited features in the web version of the app, which explains why they are not implemented.
https://webplayer.stingray.com/

Stingray media strategy.

---

BeardedSpice/AppDelegate.m
BeardedSpice/BSTrack.m

Fixes #520
Add an identifier to track notification. Allows matching track
notifications with differing contents.
Remove the previous track notification before displaying a new one.

Replace Track Notification

---

BeardedSpice/AppDelegate.m
BeardedSpice/BSTrack.h
BeardedSpice/BSTrack.m

When clicking a track notification, the user is taken to the active playing tab. Fixes #531.
Builds off PR #532:
Fixes #520
Add an identifier to track notification. Allows matching track
notifications with differing contents.
Remove the previous track notification before displaying a new one.

Clickable Track Notification

---

BeardedSpice/MediaStrategies/Eggheadio.js
BeardedSpice/MediaStrategies/versions.plist

#421 went unattended for a long time. Lots has changed and it looks like its much easier to get stuff working now. This PR adds a media strategy for Egghead.io. I've only tested this by importing the js file to BeardedSpice and everything works correctly.

Add Egghead.io media strategy

---

BeardedSpice/MediaStrategies/Spotify.js
BeardedSpice/MediaStrategies/versions.plist

The Spotify strategy was broken since the UI update.
This PR refer to the issue #631.
I added track informations that was not present in the first version.

Update the Spotify strategy #631

---

docs/developers-guide-web.md

GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1

Fix broken headings in Markdown files

---

uninstall.sh

Should fix #627 
Removes all the associated files and restarts the notification center so that bearded spice gets removed from it. Should probably be updated in the future to a more robust method of finding the app. Wasn't sure if anything should be added to the readme or not, but it can be run with `sudo ./uninstall.sh`

Adding uninstall.sh script

---

BeardedSpice/MediaStrategies/BBCRadioProgrammes.bsstrategy
BeardedSpice/MediaStrategies/versions.plist

Support for BBC's programmes site (http://www.bbc.co.uk/programmes) which is totally different than the live streaming iplayer site (http://bbc.co.uk/radio/player/)
Supports all beardedspice media strategy options and tested with several links on the site.

BBC Radio Programmes Support

---

BeardedSpice/MediaStrategies/Madsonic.js
BeardedSpice/MediaStrategies/versions.plist

I think I'm moving to Madsonic as my favorite player over Plex/Subsonic. 
Here's a strategy that is working for me locally with the latest Madsonic version, Madsonic 6.2.9080. I wish I could do it more in JS instead of DOM attr checking, but the code is pretty foreign to me.
Here's a screenshot showing the Track Info notification settings correctly working: https://files.asktherelic.com/Screen_Shot_2017-05-20_at_1.31.53_PM.png

Add madsonic strategy

---

BeardedSpice/MediaStrategies/Pandora.js
BeardedSpice/MediaStrategies/versions.plist

Currently with the Pandora new UI the pause function unconditionally clicks the play/pause button. This can lead to odd things like issue #336 and starting playback when headphones are unplugged. This patch checks to see if the button is in fact the pause button, using the same logic as other functions use, before clicking it.

Pandora: fix pause function in new UI

---

docs/developers-guide-web.md

Reminds strategy makers to add their strategy to the list in `README.md`. See the [discussion on #667](https://github.com/beardedspice/beardedspice/pull/667#issuecomment-306065806). This does not include updating `beardedspice.github.io` in [this list](https://github.com/beardedspice/beardedspice.github.io/blob/77f870b0e30f6392c2c5467319c32050f82b4740/index.html#L72) because that would require a separate PR for each strategy. I cannot think of a good solution to this other than having a bot update that list (or by using Javascript on the website).

Update developers guide

---

BeardedSpice/MediaStrategies/GoogleMusic.js
BeardedSpice/MediaStrategies/versions.plist

The selector looks a bit nasty, but it's the only way I figured. To indicate that the track is favorited, Google replaces contents of icon's SVG.
P.S. I'm not feeling confident with setting up XCode and stuff, so any help regarding testing this change will be helpful 🙂 
P.P.S. The former includes throwing at me some guide "for dummies" so I could test it myself.

Add favorited track info to GoogleMusic strategy

---

BeardedSpice/MediaStrategies/GenieMusic.js
BeardedSpice/MediaStrategies/versions.plist
README.md

Recently, Genie Music changed their player so I changed all source code for supporting new Genie Music player.

Update genie music

---

BeardedSpice/MediaStrategies/Youtube.js
BeardedSpice/MediaStrategies/versions.plist

Call functions directly on #movie_player instead of (the now removed) player_ instance.
Fixes https://github.com/beardedspice/beardedspice/issues/787

Updated Youtube play/next/previous

---

BeardedSpice/MediaStrategies/YandexMusic.js
BeardedSpice/MediaStrategies/YandexRadio.js
BeardedSpice/MediaStrategies/versions.plist

On closing the lid of laptop and some other events `pause()` method is called. So if it only toggles play/pause and if I have already paused the track, when I'll close the lid, it will resume playing. The fix is to check if current song is playing at the moment, and then stop it. This is the only way to do it since Yandex's `externalAPI` does not provide separate methods like `play()` and `pause()`.

fix: pause() in MediaStrategies for Yandex Services

---

BeardedSpiceControllers/Controllers/SPMediaKeyTap/SPMediaKeyTap.m

Currently Beardedspice would interfere with the media keys in a way that would break [Plexamp](https://plexamp.com)'s native implementation.

Add Plexamp for default Media Key Usage

---

BeardedSpice.xcodeproj/project.pbxproj
BeardedSpice/NativeAppTabRegistry.m
BeardedSpice/Tabs/QuodLibetTabAdapter.h
BeardedSpice/Tabs/QuodLibetTabAdapter.m

Quod Libet is a cross-platform GTK+-based audio player. While it doesn't support Apple scripting definitions, it _does_ expose a named-pipe based query and control API.
This tab adapter makes use of that API to query the player current status and send commands to it.
This closes #971.

Add support for Quod Libet.
